name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Android, Linux, Web
            os: ubuntu-latest
          - platform: Windows
            os: windows-latest

    name: Build and Release ${{ matrix.platform }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - if: matrix.os == 'ubuntu-latest'
        name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - if: matrix.os == 'ubuntu-latest'
        name: Configure Android signing
        shell: bash
        run: |
          if [ "${{ secrets.KEY }}" != "" ] && [ "${{ secrets.PROPERTIES }}" != "" ]; then
            cd composeApp
            echo ${{ secrets.KEY }} | base64 --decode > key.jks
            echo ${{ secrets.PROPERTIES }} | base64 --decode > key.properties
          fi

      - name: Build ${{ matrix.platform }} app
        id: build
        shell: bash
        run: |
          ./gradlew ciVersioning -Poutput=$GITHUB_OUTPUT
          ./gradlew ciReleaseApp

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: refs/tags/v${{ steps.build.outputs.version }}
          file: build/assets/*
          file_glob: true
